steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t',
        'asia-northeast1-docker.pkg.dev/kids-468115/ar-docker-repo/taido-competition-record',
        '.'
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        'push',
        'asia-northeast1-docker.pkg.dev/kids-468115/ar-docker-repo/taido-competition-record'
      ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'taido-competition-record',
        '--image',
        'asia-northeast1-docker.pkg.dev/kids-468115/ar-docker-repo/taido-competition-record',
        '--region',
        'asia-northeast1',
        '--allow-unauthenticated',
        '--port',
        '3000',
        '--memory',
        '4Gi',
        '--cpu',
        '4',
        '--cpu-boost',
        '--no-cpu-throttling',
        '--max-instances',
        '1',
        '--min-instances',
        '0',
        '--add-cloudsql-instances',
        'kids-468115:asia-northeast1:postgres-instance',
        '--update-env-vars',
        'COMPETITION_NAME=2025_kid',
        '--update-env-vars',
        'PGSQL_DATABASE=taido_record',
        '--update-env-vars',
        'PGSQL_HOST=localhost',
        '--update-env-vars',
        'PGSQL_PASSWORD=postgres',
        '--update-env-vars',
        'PGSQL_USER=postgres',
        '--update-env-vars',
        'PRODUCTION=1',
        '--update-env-vars',
        'PRODUCTION_TEST=0',
        '--update-env-vars',
        'SHOW_AWARD_IN_PUBLIC=1',
        '--update-env-vars',
        'SHOW_TOTAL_IN_ADMIN=1',
        '--update-env-vars',
        'SHOW_TOTAL_IN_PUBLIC=1',
        '--update-env-vars',
        'SHOW_HIGHLIGHT_IN_TOURNAMENT=0',
        '--update-env-vars',
        'USE_RESULT_DATA=1',
        '--update-env-vars',
        'REDISHOST=localhost',
        '--update-env-vars',
        'REDISPORT=6379',
        '--update-env-vars',
        'USE_LOCAL_DB=0',
        '--update-env-vars',
        'USE_LOCAL_REDIS=1',
        '--update-env-vars',
        'USERNAME=kids',
        '--update-env-vars',
        'PASSWORD=kesennuma2508'
      ]

images:
  - asia-northeast1-docker.pkg.dev/kids-468115/ar-docker-repo/taido-competition-record

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
