steps:
  - name: gcr.io/cloud-builders/git
    args:
      - submodule
      - update
      - --init
      - --recursive

  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_REPO_NAME/$IMAGE_NAME',
        'taido-competition-record'
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        'push',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_REPO_NAME/$IMAGE_NAME'
      ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '$CLOUD_RUN_DEPLOY_NAME',
        '--image',
        'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_REPO_NAME/$IMAGE_NAME',
        '--region',
        'asia-northeast1',
        '--allow-unauthenticated',
        '--port',
        '3000',
        '--memory',
        '4Gi',
        '--cpu',
        '4',
        '--cpu-boost',
        '--no-cpu-throttling',
        '--max-instances',
        '1',
        '--min-instances',
        '0',
        '--add-cloudsql-instances',
        '$PROJECT_ID:asia-northeast1:$CLOUDSQL_INSTANCE_ID',
        '--update-env-vars',
        'COMPETITION_NAME=$COMPETITION_NAME',
        '--update-env-vars',
        'PGSQL_DATABASE=postgres',
        '--update-env-vars',
        'PGSQL_HOST=/cloudsql/$PROJECT_ID:asia-northeast1:$CLOUDSQL_INSTANCE_ID',
        '--update-env-vars',
        'PGSQL_PASSWORD=postgres',
        '--update-env-vars',
        'PGSQL_USER=postgres',
        '--update-env-vars',
        'PRODUCTION=1',
        '--update-env-vars',
        'PRODUCTION_TEST=0',
        '--update-env-vars',
        'REDISHOST=$REDISHOST',
        '--update-env-vars',
        'REDISPORT=6379',
        '--update-env-vars',
        'USE_LOCAL_DB=0',
        '--update-env-vars',
        'USE_LOCAL_REDIS=$USE_LOCAL_REDIS',
        '--update-env-vars',
        'USERNAME=$USERNAME',
        '--update-env-vars',
        'PASSWORD=$PASSWORD',
        '--update-env-vars',
        'SHOW_TOTAL_IN_ADMIN=$SHOW_TOTAL',
        '--update-env-vars',
        'SHOW_TOTAL_IN_PUBLIC=0',
        '--update-env-vars',
        'SHOW_AWARD_IN_PUBLIC=0',
        '--update-env-vars',
        'USE_RESULT_DATA=0',
        '--update-env-vars',
        'SHOW_HIGHLIGHT_IN_TOURNAMENT=1'
      ]

images:
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_REPO_NAME/$IMAGE_NAME

options:
  logging: CLOUD_LOGGING_ONLY
