name: CI/CD
on:
  push:
    branches:
    - master
    - fix-deploy-doc
    paths:
    - "doc/**.md"
    - "book.toml"
    - ".github/actions/build/Dockerfile"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: ./.github/actions/build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: KazutoMurase/KazutoMurase.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./book
